
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Frame frame4;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.SpinButton eventno;
	
	private global::Gtk.Button genbutton;
	
	private global::Gtk.Label GtkLabel1;
	
	private global::Gtk.Frame frame5;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Frame frame13;
	
	private global::Gtk.Alignment GtkAlignment9;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Frame frame7;
	
	private global::Gtk.Alignment GtkAlignment3;
	
	private global::Gtk.ComboBoxEntry birthplace;
	
	private global::Gtk.Label GtkLabel4;
	
	private global::Gtk.Frame frame8;
	
	private global::Gtk.Alignment GtkAlignment4;
	
	private global::Gtk.ComboBoxEntry childenvironment;
	
	private global::Gtk.Label GtkLabel5;
	
	private global::Gtk.Label GtkLabel10;
	
	private global::Gtk.Frame frame9;
	
	private global::Gtk.Alignment GtkAlignment5;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Frame frame10;
	
	private global::Gtk.Alignment GtkAlignment6;
	
	private global::Gtk.ComboBoxEntry careorigin;
	
	private global::Gtk.Label GtkLabel7;
	
	private global::Gtk.Frame frame11;
	
	private global::Gtk.Alignment GtkAlignment7;
	
	private global::Gtk.ComboBoxEntry carebackground;
	
	private global::Gtk.Label GtkLabel8;
	
	private global::Gtk.Frame frame12;
	
	private global::Gtk.Alignment GtkAlignment8;
	
	private global::Gtk.ComboBoxEntry carestatus;
	
	private global::Gtk.Label GtkLabel9;
	
	private global::Gtk.Label GtkLabel6;
	
	private global::Gtk.Frame frame14;
	
	private global::Gtk.Alignment GtkAlignment10;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.SpinButton siblingct;
	
	private global::Gtk.Fixed fixed7;
	
	private global::Gtk.Label GtkLabel11;
	
	private global::Gtk.Label GtkLabel2;
	
	private global::Gtk.Frame frame6;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.Label GtkLabel3;
	
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("DnD Generator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 640;
		this.DefaultHeight = 480;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.notebook1.Add (this.fixed1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Dice Roll");
		this.label1.Justify = ((global::Gtk.Justification)(2));
		this.notebook1.SetTabLabel (this.fixed1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Number of events (0 for random):</b>");
		this.label3.UseMarkup = true;
		this.hbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.eventno = new global::Gtk.SpinButton (0D, 12D, 1D);
		this.eventno.CanFocus = true;
		this.eventno.Name = "eventno";
		this.eventno.Adjustment.PageIncrement = 3D;
		this.eventno.ClimbRate = 1D;
		this.eventno.Numeric = true;
		this.hbox1.Add (this.eventno);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.eventno]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.genbutton = new global::Gtk.Button ();
		this.genbutton.CanFocus = true;
		this.genbutton.Name = "genbutton";
		this.genbutton.UseUnderline = true;
		this.genbutton.BorderWidth = ((uint)(3));
		this.genbutton.Label = global::Mono.Unix.Catalog.GetString ("GENERATE");
		this.hbox1.Add (this.genbutton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.genbutton]));
		w4.Position = 2;
		w4.Fill = false;
		this.GtkAlignment.Add (this.hbox1);
		this.frame4.Add (this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Options</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel1;
		this.vbox3.Add (this.frame4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.frame13 = new global::Gtk.Frame ();
		this.frame13.Name = "frame13";
		this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame13.Gtk.Container+ContainerChild
		this.GtkAlignment9 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment9.Name = "GtkAlignment9";
		this.GtkAlignment9.LeftPadding = ((uint)(12));
		// Container child GtkAlignment9.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame ();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.birthplace = global::Gtk.ComboBoxEntry.NewText ();
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Out in the Wilderness"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("A Rural Hamlet/Village"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Slave Pit"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Town"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Religious or Scholarly Institution"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Fortress"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Palace"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Major Metropolis, Capitol City"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Caravan or Other Mobile"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Alien Racial Environment"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Alien Rural City"));
		this.birthplace.AppendText (global::Mono.Unix.Catalog.GetString ("Extraplanar"));
		this.birthplace.Name = "birthplace";
		this.GtkAlignment3.Add (this.birthplace);
		this.frame7.Add (this.GtkAlignment3);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Place of Birth</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel4;
		this.hbox4.Add (this.frame7);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame7]));
		w10.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.frame8 = new global::Gtk.Frame ();
		this.frame8.Name = "frame8";
		this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame8.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.childenvironment = global::Gtk.ComboBoxEntry.NewText ();
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("No Adult Supervision"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Abusive"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Sheltered"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Supportive"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Gang"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Strict"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Owned"));
		this.childenvironment.AppendText (global::Mono.Unix.Catalog.GetString ("Apprenticed"));
		this.childenvironment.Name = "childenvironment";
		this.GtkAlignment4.Add (this.childenvironment);
		this.frame8.Add (this.GtkAlignment4);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Childhood Environment</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame8.LabelWidget = this.GtkLabel5;
		this.hbox4.Add (this.frame8);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame8]));
		w13.Position = 1;
		this.GtkAlignment9.Add (this.hbox4);
		this.frame13.Add (this.GtkAlignment9);
		this.GtkLabel10 = new global::Gtk.Label ();
		this.GtkLabel10.Name = "GtkLabel10";
		this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Birth &amp; Childhood</b>");
		this.GtkLabel10.UseMarkup = true;
		this.frame13.LabelWidget = this.GtkLabel10;
		this.hbox2.Add (this.frame13);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame13]));
		w16.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.frame9 = new global::Gtk.Frame ();
		this.frame9.Name = "frame9";
		this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame9.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.frame10 = new global::Gtk.Frame ();
		this.frame10.Name = "frame10";
		this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame10.Gtk.Container+ContainerChild
		this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment6.Name = "GtkAlignment6";
		this.GtkAlignment6.LeftPadding = ((uint)(12));
		// Container child GtkAlignment6.Gtk.Container+ContainerChild
		this.careorigin = global::Gtk.ComboBoxEntry.NewText ();
		this.careorigin.AppendText (global::Mono.Unix.Catalog.GetString ("Original Parents"));
		this.careorigin.AppendText (global::Mono.Unix.Catalog.GetString ("Close Family"));
		this.careorigin.AppendText (global::Mono.Unix.Catalog.GetString ("Adopted"));
		this.careorigin.AppendText (global::Mono.Unix.Catalog.GetString ("Institution"));
		this.careorigin.AppendText (global::Mono.Unix.Catalog.GetString ("Master"));
		this.careorigin.AppendText (global::Mono.Unix.Catalog.GetString ("On Your Own"));
		this.careorigin.Name = "careorigin";
		this.GtkAlignment6.Add (this.careorigin);
		this.frame10.Add (this.GtkAlignment6);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Caretaker\'s Origin</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame10.LabelWidget = this.GtkLabel7;
		this.hbox3.Add (this.frame10);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame10]));
		w19.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.frame11 = new global::Gtk.Frame ();
		this.frame11.Name = "frame11";
		this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame11.Gtk.Container+ContainerChild
		this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment7.Name = "GtkAlignment7";
		this.GtkAlignment7.LeftPadding = ((uint)(12));
		// Container child GtkAlignment7.Gtk.Container+ContainerChild
		this.carebackground = global::Gtk.ComboBoxEntry.NewText ();
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Homeless"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Entertainers"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Serfs/Servants"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Free Labourers"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Monks or Scholars"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Military"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Tradesman"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Guild"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Merchant"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Minor Noble"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Major Noble"));
		this.carebackground.AppendText (global::Mono.Unix.Catalog.GetString ("Royalty"));
		this.carebackground.Name = "carebackground";
		this.GtkAlignment7.Add (this.carebackground);
		this.frame11.Add (this.GtkAlignment7);
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Caretaker\'s Background</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame11.LabelWidget = this.GtkLabel8;
		this.hbox3.Add (this.frame11);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame11]));
		w22.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.frame12 = new global::Gtk.Frame ();
		this.frame12.Name = "frame12";
		this.frame12.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame12.Gtk.Container+ContainerChild
		this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment8.Name = "GtkAlignment8";
		this.GtkAlignment8.LeftPadding = ((uint)(12));
		// Container child GtkAlignment8.Gtk.Container+ContainerChild
		this.carestatus = global::Gtk.ComboBoxEntry.NewText ();
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Cult"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Addiction"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Crippled"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Cursed"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Taken"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Indentured Servant"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Bankruptcy"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Crazy"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Prison"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Died during Warfare"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Died of a Disease"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Died of an Accident"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Murdered"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Died by Unknown Causes"));
		this.carestatus.AppendText (global::Mono.Unix.Catalog.GetString ("Murdered by You"));
		this.carestatus.Name = "carestatus";
		this.GtkAlignment8.Add (this.carestatus);
		this.frame12.Add (this.GtkAlignment8);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Caretaker\'s Status</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame12.LabelWidget = this.GtkLabel9;
		this.hbox3.Add (this.frame12);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.frame12]));
		w25.Position = 2;
		this.GtkAlignment5.Add (this.hbox3);
		this.frame9.Add (this.GtkAlignment5);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Family History</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame9.LabelWidget = this.GtkLabel6;
		this.hbox2.Add (this.frame9);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame9]));
		w28.Position = 1;
		this.vbox5.Add (this.hbox2);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame14 = new global::Gtk.Frame ();
		this.frame14.Name = "frame14";
		this.frame14.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame14.Gtk.Container+ContainerChild
		this.GtkAlignment10 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment10.Name = "GtkAlignment10";
		this.GtkAlignment10.LeftPadding = ((uint)(12));
		// Container child GtkAlignment10.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 1F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Number of Siblings:</b>");
		this.label5.UseMarkup = true;
		this.hbox5.Add (this.label5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
		w30.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.siblingct = new global::Gtk.SpinButton (0D, 12D, 1D);
		this.siblingct.CanFocus = true;
		this.siblingct.Name = "siblingct";
		this.siblingct.Adjustment.PageIncrement = 3D;
		this.siblingct.ClimbRate = 1D;
		this.siblingct.Numeric = true;
		this.hbox5.Add (this.siblingct);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.siblingct]));
		w31.Position = 1;
		w31.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.hbox5.Add (this.fixed7);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed7]));
		w32.Position = 2;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		this.GtkAlignment10.Add (this.vbox6);
		this.frame14.Add (this.GtkAlignment10);
		this.GtkLabel11 = new global::Gtk.Label ();
		this.GtkLabel11.Name = "GtkLabel11";
		this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Siblings</b>");
		this.GtkLabel11.UseMarkup = true;
		this.frame14.LabelWidget = this.GtkLabel11;
		this.vbox5.Add (this.frame14);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame14]));
		w36.Position = 1;
		this.GtkAlignment1.Add (this.vbox5);
		this.frame5.Add (this.GtkAlignment1);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Background</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel2;
		this.vbox3.Add (this.frame5);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame5]));
		w39.Position = 1;
		w39.Expand = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame ();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		this.frame6.Add (this.GtkAlignment2);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Events</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel3;
		this.vbox3.Add (this.frame6);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame6]));
		w41.Position = 2;
		this.notebook1.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox3]));
		w42.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Story Generator");
		this.label2.Justify = ((global::Gtk.Justification)(2));
		this.notebook1.SetTabLabel (this.vbox3, this.label2);
		this.label2.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
